### PR TITLE
fix #161, use the sentry isolation scope instead of the deprecated hub

### LINKED ISSUE #161: migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
/home/app/venv/lib/python3.12/site-packages/structlog_sentry/__init__.py:111: SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
  return self._hub or Hub.current

Sentry SDK version: 2.12.0
structlog-sentry version: 2.1.0

### PR DESCRIPTION
**Pull request by arthurdarcet**

### CODE REVIEW

**Comment by paveldedik** [comment]
Hi @arthurdarcet thank you for the contribution! Could you check the failing pipeline please?

**Comment by arthurdarcet** [comment]
@paveldedik should be fine now

**Comment by paveldedik** [comment]
@arthurdarcet thank you, only Ruff is failing now, can you check please? :)

**Comment by arthurdarcet** [comment]
Lint should be ok now

**Pull request merged**
