### PR TITLE
fix: compatibility with newer Sentry SDKs

### PR DESCRIPTION
**Pull request by jyggen**
This should fix the issue seen in #112.

### CODE REVIEW

**Review by paveldedik — APPROVED** [review]
Thank you, it looks great :-)

**Review by paveldedik — CHANGES_REQUESTED** [review]
Please fix the commit message so that the pipeline passes :-) we use https://www.conventionalcommits.org/en/v1.0.0/

**Comment by jyggen** [comment]
Done!

**Comment by paveldedik** [comment]
There seems to be an issue with pre-commit, it is not your issue, I'll try to fix it here - https://github.com/kiwicom/structlog-sentry/pull/114 I'll fix it and merge this one soon :-)

**Comment by paveldedik** [comment]
I had to merge it as part of https://github.com/kiwicom/structlog-sentry/pull/114 but it is merged, thank you for your contribution :-)

**Pull request closed without merging**
